user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

gratitude:
    resource: "@GratitudeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
