<?php

namespace GratitudeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GratitudeListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GratitudeListRepository extends EntityRepository
{
}
